
name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    - name: Checkmarx AST Github Action
      uses: Checkmarx/ast-github-action@2.0.3
      with:
    
    base_uri: 
    https://eu.ast.checkmarx.net
    cx_tenant: ps_tenant
    cx_client_id: ${{ secrets.CLIENT_ID }}
    cx_client_secret: ${{ secrets.CLIENT_SECRET }}
    project_name: ${{ github.repository }}
    branch: ${{ github.ref }}
    github_token: ${{ github.token }}
    additional_params:--file-filter !readme --report-format sarif --output-name results
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: <GitHub Training>
          cx_tenant: <ps_tenant>
          base_uri: <https://eu.ast.checkmarx.net> 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
